name: ci
on: push:
env:
  DEFAULT_GO_VERSION: 1.15
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
      - name: Checkout Code
        uses: actions/checkout@v2
      # - name: Run test
      #   run: go test ./...
      - name: Build
        run: go build